version: '3'

services:
  appclose:
    build: .
    environment:
      - LIMIT=${LIMIT:-2}
      - WAIT_TIME=${WAIT_TIME:-10}
      - MASK=${MASK:-24}
    ports:
      - 8080:8080
    image: "appclose"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
